mysite/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path

from polls import views

urlpatterns = [
    path('', RedirectView.as_view(url='polls/', permanent=False)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/sign_up/', views.sign_up, name='sign_up'),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models/auth_user.py
from django.contrib.auth.models import User
from django.db import models
from django.http import HttpRequest

from .choice import Choice
from .question import Question
from .vote import Vote


class AuthorizedUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def can_vote(self, request: HttpRequest, question: Question) -> bool:
        """
        Check if the user can vote on a given question.

        Args:
            request (HttpRequest): The HTTP request object.
            question (Question): The question to check for voting eligibility.

        Returns:
            bool: True if the user can vote, False otherwise.
        """
        return question.is_published() and request.user.is_authenticated

    def get_existing_vote(self, request: HttpRequest, question: Question) -> 'Vote':
        """
        Get the existing vote of the user for a given question.

        Args:
            request (HttpRequest): The HTTP request object.
            question (Question): The question to retrieve the vote for.

        Returns:
            Vote: The existing vote of the user for the question, or None if no vote exists.
        """
        existing_vote = Vote.objects.filter(user=request.user,
                                        choice__question=question).first()
        return existing_vote

    def submit_vote(self, request: HttpRequest, question: Question) -> None:
        """
        Submit a vote for the user on a given question.

        Args:
            request (HttpRequest): The HTTP request object.
            question (Question): The question to vote on.
        """
        if self.can_vote(request, question):
            new_choice = Choice.objects.get(pk=request.POST["choice"])
            existing_vote = self.get_existing_vote(request, question)

            if existing_vote is None:
                new_vote = Vote(user=request.user, choice=new_choice)
                new_vote.save()
            else:
                existing_vote.choice = new_choice
                existing_vote.save()

            self.update_session(request, question)

    def update_session(self, request: HttpRequest, question: Question) -> None:
        """
        Update the session with the user's recent question and choice.

        Args:
            request (HttpRequest): The HTTP request object.
            question (Question): The question that the user voted on.
        """
        recent_question_ids = request.session.get('recent_question_ids', [])
        recent_choice_ids = request.session.get('recent_choice_ids', [])

        try:
            index = recent_question_ids.index(question.id)
            recent_choice_ids[index] = int(request.POST["choice"])
        except ValueError:
            recent_question_ids.append(int(question.id))
            recent_choice_ids.append(int(request.POST["choice"]))

        request.session['recent_question_ids'] = recent_question_ids
        request.session['recent_choice_ids'] = recent_choice_ids

polls/models/choice.py
from django.core.exceptions import ValidationError
from django.db import models


class Choice(models.Model):
    """
    Model representing choices for a poll question.
    """
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    @property
    def votes(self) -> int:
        """
        Get the number of votes for this choice.

        Returns:
            int: The number of votes.
        """
        return self.vote_set.count()

    def clean(self) -> None:
        """
        Custom validation to ensure that the choice_text is unique among existing choices.
        Raises a ValidationError if the choice_text is not unique.
        """
        text_exists = Choice.objects.filter(question=self.question,
                                            choice_text__iexact=self.choice_text).exists()

        if text_exists:
            raise ValidationError("Choice with this text already exists.")

    def save(self, *args, **kwargs) -> None:
        """
        Override the save method to ensure clean() is called before saving.
        """
        self.clean()
        super().save(*args, **kwargs)

    def get_percentage_vote(self) -> float:
        """
        Calculate the percentage of votes for this choice among all votes for the question.

        Returns:
            float: The percentage of votes for this choice.
        """
        all_votes = self.question.get_all_votes()
        if all_votes == 0:
            return 0
        
        return (self.votes / all_votes) * 100

    def __str__(self) -> str:
        """
        Return a string representation of the choice.

        Returns:
            str: The choice text.
        """
        return self.choice_text

polls/models/question.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from .choice import Choice
from .vote import Vote


def now_plus(added_day: int = 0) -> datetime:
    """
    Return the current time with an optional offset in days.
    """
    return timezone.now() + timezone.timedelta(days=added_day)


class Question(models.Model):
    """
    Model representing a poll question.
    """
    def pub_date_default() -> datetime:
        """
        Default value for the 'pub_date' field.
        """
        return now_plus(0)

    def end_date_default() -> datetime:
        """
        Default value for the 'end_date' field.

        Returns:
            datetime: The current time plus one day.
        """
        return now_plus(1)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=pub_date_default,
                                    verbose_name='published date')
    end_date = models.DateTimeField(default=end_date_default,
                                    verbose_name='end date')

    def clean(self) -> None:
        """
        Custom validation to ensure pub_date is earlier than end_date.
        """
        if self.pub_date >= self.end_date:
            raise ValidationError("The 'published date' must be earlier than the 'end date'.")

    def save(self, *args, **kwargs) -> None:
        """
        Override the save method to ensure clean() is called before saving.
        """
        self.clean()
        super().save(*args, **kwargs)

    def was_published_recently(self) -> bool:
        """
        Check if the question was published within the last 24 hours.

        Returns:
            bool: True if the question was published recently, False otherwise.
        """
        return now_plus(-1) <= self.pub_date <= now_plus(0)

    def is_published(self) -> bool:
        """
        Check if the question is currently published.

        Returns:
            bool: True if the question is published, False otherwise.
        """
        return self.pub_date <= now_plus(0) <= self.end_date

    def get_remaining_time(self) -> str:
        """
        Return the time remaining (time difference) until a poll ends.
        If a poll has ended, it will return zero time difference.

        Returns:
            str: The remaining time as formatted string without microseconds.
        """
        remaining_time = max(self.end_date - now_plus(0), timezone.timedelta(0))
        return str(remaining_time).split(".")[0]

    def get_all_votes(self) -> int:
        """
        Get the total number of votes for this question.

        Returns:
            int: The total number of votes.
        """
        related_choices = Choice.objects.filter(question=self)
        all_votes = Vote.objects.filter(choice__in=related_choices).count()
        return all_votes

    def __str__(self) -> str:
        """
        Return a string representation of the question.

        Returns:
            str: The question text.
        """
        return self.question_text

polls/models/vote.py
from django.contrib.auth.models import User
from django.db import models

from .choice import Choice


class Vote(models.Model):
    """
    Records a Vote.
    """
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from django.db.models.query import QuerySet
from django.http import Http404, HttpRequest, \
                        HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models.auth_user import AuthorizedUser
from .models.choice import Choice
from .models.question import Question


class IndexView(generic.ListView):
    """
    View for displaying a list of the latest poll questions.
    """
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self) -> QuerySet[Question]:
        """
        Return all the published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    """
    View for displaying the details of a poll question.
    """
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self) -> QuerySet[Question]:
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get(self, request, *args, **kwargs) -> HttpResponse | HttpResponseRedirect:
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            messages.error(request, "You don't have access to that page")
            return redirect(reverse('polls:index'))


class ResultsView(generic.DetailView):
    """
    View for displaying the results of a poll question.
    """
    model = Question
    template_name = 'polls/results.html'


def sign_up(request) -> HttpResponse | HttpResponseRedirect:
    """
    View for user registration.
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            return redirect(reverse('polls:index'))

        else:
            for each_error in form.errors.values():
                messages.error(request, each_error)

    else:
        form = UserCreationForm()

    return render(request, "registration/sign_up.html")


@login_required
def vote(request: HttpRequest, question_id: int) -> HttpResponseRedirect:
    """
    View for submitting votes on poll questions.
    """
    try:
        question = get_object_or_404(Question, pk=question_id)
        authorized_user = AuthorizedUser()

        if authorized_user.can_vote(request, question):
            authorized_user.submit_vote(request, question)
            messages.success(request, 'Vote has been successfully submitted.')
            return redirect(reverse('polls:results', args=(question.id,)))
        else:
            messages.error(request, "Voting on this poll is not allowed.")

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        messages.error(request, "You didn't select a choice.")

    return redirect(reverse('polls:detail', args=(question.id,)))

polls/templates/polls/detail.html
{% extends "polls/layout.html" %}

{% block body %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
    <div class="list-group">
        {% for choice in question.choice_set.all %}
        <div class="list-group-item form-check">
            <div class="ml-3">
                <input class="form-check-input" type="radio" name="choice"
                id="choice{{ forloop.counter }}" value="{{ choice.id }}" 

                {% if choice.id in request.session.recent_choice_ids %}
                    checked
                {% endif %}>

                <label class="h6 form-check-label" for="choice{{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label>
            </div>
        </div>
        {% endfor %}
    </div>
    </fieldset><br>
    
    <input class="btn btn-success" type="submit" value="Vote">
</form>

<form action="{% url 'polls:results' question.id %}">
    <input class="btn btn-primary" type="submit" value="View Results">
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/layout.html" %}

{% block poll_info %}
{% endblock %}

{% block body %}
<h1> Poll List </h1>
{% for question in latest_question_list %}
    <a class="list-group-item list-group-item-action
        {% if not question.is_published %} 
            list-group-item-secondary
        {% endif %}"
        {% if question.is_published %} 
            href="{% url 'polls:detail' question.id %}"
        {% endif %}
    >

        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"> {{ question.question_text }}
                {% if question.is_published %}
                    <span class="badge badge-success">Open</span>
                {% else %}
                    <span class="badge badge-secondary">Closed</span>
                {% endif %}
                {% if question.was_published_recently %}
                    <span class="badge badge-danger">New</span>
                {% endif %}
            </h5>
            <small class="mt-1">Created on {{ question.pub_date }}</small>
        </div>

        <div class="d-flex w-100 justify-content-between">
            <small class="mb-2">This poll ends in {{ question.get_remaining_time }} </small>
            <small class="mb-2">Ends on {{ question.end_date }}</small>
        </div>

        <div class="d-flex w-100 justify-content-between">
            Total votes: {{ question.get_all_votes }}
            <form action="{% url 'polls:results' question.id %}">
                <input class="btn-primary" type="submit" value="View Results">
            </form>
        </div>
    </a>
    {% empty %}
        <p>No polls are available.</p>
    {% endfor %}
{% endblock %}

polls/templates/polls/layout.html
<!DOCTYPE html>
<html lang="en">
    {% block head %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Link to Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        
        <title> KU Polls </title>
    </head>
    {% endblock %}

    <body>
        {% block navbar %}
        <nav class="navbar bg-light nav-fill">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="h5 nav-link active" href={% url "polls:index" %}>Poll List</a>
                </li>
            </ul>

            <nav class="h5 bg-light">
                {% if user.is_authenticated %}
                    <form class="d-flex" action="{% url 'logout' %}">
                        <span class="h5 mt-3 mr-3"> Welcome back, {{ user.username }}</span>
                        <button class="mt-2 btn btn-dark" type="submit">Logout</button>
                    </form>
                {% else %}
                    <form class="d-flex" action="{% url 'login' %}">
                        <span class="h5 mt-3 mr-3"> Please Login</span>
                        <button class="mt-2 btn btn-dark" type="submit">Login</button>
                    </form>
                {% endif %}
            </nav>
        </nav>
        {% endblock %}
        
        {% block messages %}
        {% if messages %}
        <div class="mx-4 my-2 messages">
            {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="alert alert-danger">
                {% else %}
                <div class="alert alert-{{ message.tags }}">
                {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endblock %}

        <div class="mx-4 my-2">
            {% block poll_info %}                
                <h2 class="my-1">{{ question.question_text }}</h2>
                <h4>
                {% if question.is_published %}
                    <span class="mb-2 badge badge-success">Open</span>
                {% else %}
                    <span class="badge badge-secondary">Closed</span>
                {% endif %}
            
                {% if question.was_published_recently %}
                    <span class="badge badge-danger">New</span>
                {% endif %}
                </h4>
            
                <div class="d-flex w-100 justify-content-between">
                    <span>This poll ends in {{ question.get_remaining_time }}</span>
                    <span class="mt-1">Created on {{ question.pub_date }}</span>
                </div>
            
                <div class="d-flex w-100 justify-content-between">
                    <span> </span>
                    <span>Ends on {{ question.end_date }}</span>
                </div><br>
            {% endblock %}
            
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
            
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

polls/templates/polls/results.html
{% extends "polls/layout.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <table class="table text-center table-bordered table-striped">
                <tr class="table-secondary">
                    <th>Choice</th>
                    <th>Vote</th>
                </tr>
                {% for choice in question.choice_set.all %}
                <tr>
                    <td>{{ choice.choice_text }}</td>
                    <td>{{ choice.votes }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <div class="col">
            <div class="card">
                <div class="h5 card-header d-flex justify-content-start">
                    <span> Total Votes</span>
                    <span class="badge badge-success mx-1"></span>
                </div>

                <div class="card-body">
                    <h5 class="card-title">Options</h5>
                    {% for choice in question.choice_set.all %}
                    <div class="h5 progress" style="height: 30px;">
                        <div class="progress-bar" style="width: {{ choice.get_percentage_vote }}%;">
                            {{ choice.choice_text }} ({{ choice.get_percentage_vote|floatformat:2 }}%)
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% if user.is_authenticated and question.is_published %}
<form action="{% url 'polls:detail' pk=question.pk %}">
    <input class="btn btn-info" type="submit" value="Change your vote">
</form>
{% endif %}

<form action="{% url 'polls:index' %}">
    <input class="btn btn-primary" type="submit" value="Back to Poll List">
</form>

{% endblock %}